language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - sudo apt-get -y install libvlc-dev
  - whereis vlc
  - echo $PATH
addons:
  apt:
    update: true

os:
- linux

smalltalk:
  - Pharo64-8.0
