language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - sudo apt install snap -y
  - sudo snap install vlc
  - whereis libvlc
  - whereis libvlccore
  - echo $PATH
addons:
  apt:
    update: true

os:
- linux

smalltalk:
  - Pharo64-8.0
